### PR TITLE
fix: publish only a single stop on new subscription

### LINKED ISSUE #310: Opening a stop clears departures of other users
- open app on two devices
- open a stop on both devices
- 💥 opening on second device clears list of first device for a brief moment

### PR DESCRIPTION
**Pull request by lukashass**
Closes #310

### CODE REVIEW

File: collectors/kvg/collector/collector.go [hunk 1]
```diff
@@ -8,7 +8,9 @@ import (
 )
 
 type Collector interface {
-	Run(IDs []string, runRemove bool)
+	Run(IDs []string)
+	RunSingle(ID string)
+	SubjectToID(subject string) string
 	SubjectsToIDs(subjects []string) []string
```
Comment (anbraten) [inline collectors/kvg/collector/collector.go:14]: Should we remove subject to ids now as we could simply use `SubjectToID` on the array?

File: collectors/kvg/collector/stop.go [hunk 2]
```diff
@@ -155,3 +163,29 @@ func (c *StopCollector) Run(stopIDs []string, _ bool) {
 	// update list of stops
 	c.stops = stops
 }
+
+func (c *StopCollector) RunSingle(stopID string) {
+	log := logrus.WithField("collector", "stop")
```
Comment (anbraten) [inline collectors/kvg/collector/stop.go:168]:
```suggestion
	log := logrus.WithField("collector", "stop").WithField("stop-id", stopID)
```

File: collectors/kvg/collector/trip.go [hunk 3]
```diff
@@ -117,20 +125,37 @@ func (c *TripCollector) Run(tripIDs []string, runRemoved bool) {
...
 		}
 	}
 
 	log.Debugf("changed %d trips and removed %d", len(changed), len(removed))
 	// update list of trips
 	c.trips = trips
 }
+
+func (c *TripCollector) RunSingle(tripID string) {
+	log := logrus.WithField("collector", "trip")
```
Comment (anbraten) [inline collectors/kvg/collector/trip.go:143]:
```suggestion
	log := logrus.WithField("collector", "trip").WithField("trip-id", tripID)
```

**Review by anbraten — APPROVED** [review]
